collections:
  authors:
    output: true
  projects:
    output: true
  tutorials:
    output: true
  parametersets:
    output: true
  files:
    output: true  

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "staffpage"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

## This is a hardcode fix around an error I couldn't solve where the metadeta for the index page wasn't being read. 
## As a result, any page without a layout, title, heading or sidebar list (it can be empty) will defaul to these values.
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Home"
      heading: "DFTBML"
      sidebar: ["What is DFTBML?", "What Makes DFTBML Different?", "Learn More!"]

  - scope:
      path: ""
      type: "parametersets"
    values:
      name: ""