collections:
  authors:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name
  tutorials:
    output: true
    permalink: /:collection/:name
  parametersets:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "staffpage"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

## This is a hardcode fix around an error I couldn't solve where the metadeta for the index page wasn't being read. 
## As a result, any page without a layout, title, heading or sidebar list (it can be empty) will default to these values.
## Couldn't figure out how to fix it unfortunately except to change the permalink of the Index page.
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Home"
      heading: "DFTBML"
      sidebar: ["What is DFTBML?", "What Makes DFTBML Different?", "Learn More!"]