collections:
  authors:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "staffpage"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Home"
      heading: "DFTBML"
      sidebar: [What is DFTBML?, What Makes DFTBML Different?, Learn More!]