collections:
  authors:
    output: true
  projects:
    output: true
  tutorials:
    output: true
  parametersets:
    output: true
  files:
    output: true  

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "staffpage"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
    values:
      layout: "default"
      title: "Home"
      heading: "DFTBML"
      sidebar: ["What is DFTBML?", "What Makes DFTBML Different?", "Learn More!"]

  - scope:
      path: ""
      type: "parametersets"
    values:
      name: ""